title: Codekit
# subTitle: Subtitle

#Debugging
log: false
# logFile: 'hugo-debug.log'
verbose: false
verboseLog: false
uglyURLs: true # make simple HTML files not directories

#=====================================

#for Local
# baseURL: ""
# RelativeURLs: true # rewrite to relative to root of content
# canonifyURLs: false # switch to true to prefix URLs with baseURL

#For Package
baseURL: "/"
RelativeURLs: false # rewrite to relative to root of content
canonifyURLs: true # switch to true to prefix URLs with baseURL

#=====================================

# Defualt Outputs
disableKinds: ["RSS", "404", "sitemap", "robotsTXT"]

# Content Settings
MetaDataFormat: "yaml"
pluralizeListTitles: false
author: Lex Semenenko

# Markdown
blackfriday:
  plainIDAnchors: true
  smartypants: true
  smartDashes: true
  fractions: false # Formats expressions like 2/3
  angledQuotes: true # Actual quote marks
  taskLists: false
  hrefTargetBlank: false # Only works with site having relative URLs
  nofollowLinks: false # Only works with site having relative URLs
  latexDashes: true # Deals with em & en dashes working correctly
  noreferrerLinks: false # Only works with site having relative URLs
  extensions:
  extensionsmask: ["autoHeaderIds"] # Removes header IDs that are added automatically. Required for TOC to work

# Global Variables
Params:
  package: false
  path:
    images: "/images/"
    files: "/files/"

# =============================================================================
# Menu
# =============================================================================

menu:
  # Main
  # =============================================================================

  main:
    # Level One
    # =====================================

    - name: "Home"
      weight: 1
      url: "/"
      identifier: "home"
    - name: "Demo"
      weight: 1
      url: javascript:;
      identifier: "demo"
    - name: "Playground"
      weight: 1
      url: javascript:;
      identifier: "Playground"
    - name: "Snippets"
      weight: 1
      url: javascript:;
      identifier: "home"

    # Playground Children
    # =====================================
    - name: "JS"
      identifier: "playground_js"
      url: javascript:;
      parent: "Playground"

    # JS Children
    # -------------------------------------
    - name: "Objects"
      identifier: "playground_js_objects"
      url: javascript:;
      parent: "playground_js"
    - name: "Object Methods"
      identifier: "playground_js_object_methods"
      url: javascript:;
      parent: "playground_js"
    - name: "Types"
      identifier: "playground_js_types"
      url: javascript:;
      parent: "playground_js"
    - name: "Functions"
      identifier: "playground_js_functions"
      url: javascript:;
      parent: "playground_js"
    - name: "This"
      identifier: "playground_js_this"
      url: javascript:;
      parent: "playground_js"
    - name: "Constructor & Prototypes"
      identifier: "playground_js_constructor_prototypes"
      url: javascript:;
      parent: "playground_js"
