backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "src/img/projects" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "project" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Project" # Used in the UI, ie.: "New Post"
    folder: "site/content/project" # The path to the folder where the documents are stored
    extension: "md"
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - { label: "Name", name: "name", widget: "string" }