backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "src/img/projects" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "project" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Project" # Used in the UI, ie.: "New Post"
    folder: "site/content/project" # The path to the folder where the documents are stored
    extension: "md"
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - { label: "Company Name", name: "company_name", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Project Date", name: "project_date", widget: "datetime" }
      - { label: "Intro", name: "intro", widget: "markdown", required: false }
      - { label: "Link", name: "link", widget: "markdown", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - label: Project Thumbnail
        name: project_thumbnail
        widget: image
        required: false
        options:
          media_library:
            config:
              multiple: true
              previewStep: false